### ISSUE TITLE
sofa-pbrpc支持http协议，在路由阶段有些不符合预期的地方

### ISSUE THREAD

**Issue by zhangxiang02** [baidu/sofa-pbrpc#103]
/a/b
/a/c
使用上述两个路径同时注册，后一个会注册失败
另外/a/*  可以匹配/a对应WebServlet这个实现需要斟酌一下，这样会导致以下问题
例如  我注册了一个 /a
同时我也注册了/a/b , /a/c 这个时候一切都符合预期
如果我没有注册 /a 这个时候注册 /a/b , /a/c 这个时候 第二个注册会失败
建议http路径解析不需要这样的容错逻辑，其下可能隐藏bug，即耗费性能，用户很少会去直接输url查询

**Comment by zd-double** [comment]
@zhangxiang02 多谢提出这个问题，我尽快确认处理。

**Comment by zd-double** [comment]
@zhangxiang02  上述路由失败问题已修复，请知晓
