### ISSUE TITLE
支持安全套接字通信吗，不支持的话，有计划吗？

### ISSUE THREAD

**Issue by datatechboost** [baidu/sofa-pbrpc#148]
应用场景：
a, 服务器与客户端之间采用https保证安全性
b, 部署于第三方的云主机上时服务器内部模块之间的通信安全性

**Comment by datatechboost** [comment]
或者采用咱们的pbrpc时有别的安全机制吗？

**Comment by zd-double** [comment]
@datatechboost  这个暂时不支持，不过已经安排到开发计划当中。非常欢迎你能就此提个pr ：），谢谢。

**Comment by datatechboost** [comment]
@zd-double 不好意思，这几天公司的事情太多，很高兴看到有开发计划，目前我对pbrpc还处在学习阶段，提pr还有差距，呵呵。感谢你们对pbrpc的伟大贡献。
