### ISSUE TITLE
Is 32 bit supported?

### ISSUE THREAD

**Issue by yuxiangning** [baidu/sofa-pbrpc#15]
Hi folks,

This is really good work and I'd like to try it out. While looks like it doesn't compile on 32 bit platform, it failed with following error:

src/sofa/pbrpc/atomic.h: Assembler messages:
src/sofa/pbrpc/atomic.h:59: Error: invalid instruction suffix for `xadd'
make: **\* [src/sofa/pbrpc/dynamic_rpc_channel_impl.o] Error 1

After adding -m64 flag to the Makefile, and installing 64 bit gcc library, it compiles but failed to link because there is no 64 bit protobuf library.

I could try it on a 64 bit platform, but just to want to check if 32 bit is supported or not. Thank you!

Regards
Xiangning

**Comment by taocp** [comment]
It was really a sad story :(

**Comment by qinzuoyan** [comment]
not yet, but soon :)
