### ISSUE TITLE
关于flow_control

### ISSUE THREAD

**Issue by fdxuwei** [baidu/sofa-pbrpc#165]
在默认配置下，flow_control每毫秒都会增加一个配额，当配额没有消费时，配额会越来越大，从而达不到流量控制的效果，不知道我这样理解对不对？

**Comment by qinzuoyan** [comment]
不完全是这样的。

- 配额是按需获取，由一个中心的FlowController控制，如果一个连接需要send/receive数据，就需要申请配额，只有申请成功才能执行send/receive操作
- 配额的切分粒度为100ms（称为一个时间片），即每0.1秒都将FlowController重置一次，注意是重置而不是增加，即配额没有用完就作废；其实也不是完全的重置，下面有讲
- 当配额快要用完的时候，下一条send/receive数据的大小可能超过剩余的配额，此时仍然允许执行send/receive操作，但是用超的配额会记录在那里，类似于欠账
- 在新的时间片对FlowController进行重置的时候，如果上一个时间片配额用超过了（有欠账），则需先还帐，还完后剩余的配额才是这个时间片的可用配额；如果上一个时间片没有欠账，则直接重置。
- 一句话来解释：FlowController是个精明的商人，它不记得结余，只记得欠账。通过比较保守的方式，来控制流量的上限。

希望你明白了。

**Comment by fdxuwei** [comment]
懂了，谢谢
