### ISSUE TITLE
检查 NULL 返回值

### ISSUE THREAD

**Issue by viennadd** [baidu/sofa-pbrpc#184]
我们工具扫出 [pbjson.cc#L238](https://github.com/baidu/sofa-pbrpc/blob/master/src/sofa/pbrpc/pbjson.cc#L238) parse_msg 有多个返回 NULL 的语句，但函数`pb2json` 包装 `parse_msg` 时不对返回做检查就传入 `json2string`。然后对 `parse_msg` 返回的 *json 做解引用，希望查询一下

```c
void pb2json(const Message* msg, std::string& str)
{
    rapidjson::Value::AllocatorType allocator;
    rapidjson::Value* json = parse_msg(msg, allocator);
    json2string(json, str);
    delete json;
}
```

**Comment by cyshi** [comment]
加上了 多谢 #185
