### ISSUE TITLE
server端 和 client端延时增加

### ISSUE THREAD

**Issue by namelij** [baidu/sofa-pbrpc#202]
1、client采用的是异步形式，在client调用rpc接口之前有统计一个时间，在client收到server端回复的时候的回调函数里面设置一个时间
2、client收到后，也就进行一些协议的转换，不存在io和计算，这块统计了，耗时在us级别

ps：刚才仔细统计了下，client 调用rpc接口的时候时间为 2017-07-28 11:00:56.993282
server端收到消息之后，时间为2017-07-28 11:00:56.993969，这块可以理解为网络耗时，700us左右

server端完成消息处理后的时间为 2017-07-28 11:00:56.995192,而client收到消息后的时间为2017-07-28 11:00:57.026753,这块耗时在31ms左右，现在就是不知道为什么这块耗时这么久，有没有优化的地方，比如buffer大小等  1g带宽，client 10s内收到大概不到6m字节

**Comment by qinzuoyan** [comment]
@namelij 怎么close了？问题解决了？
