### ISSUE TITLE
底层网络库为什么要用指明epoll呢？

### ISSUE THREAD

**Issue by OkamiLiu** [baidu/sofa-pbrpc#206]
底层网络库为什么要指明epoll呢？为什么不用通用io_service呢？

**Comment by zd-double** [comment]
@OkamiLiu io_service是asio中的异步事件队列用来做异步事件的分发，asio在linux平台下底层通讯还是使用的epoll+socket，详细实现可以参考下boost下asio的相关实现 :)

**Comment by LazyPlanet** [comment]
epoll+socket会有什么问题呢？影响性能吗？

**Comment by LazyPlanet** [comment]
@zd-double  谢谢。

**Comment by OkamiLiu** [comment]
@LazyPlanet 影响跨平台扩展

**Comment by LazyPlanet** [comment]
还有我发现作者一直没有使用io_srevice.run() 这个执行而是使用的io_service_work来包装io_service是不是也是出于性能的考虑？谢谢。
