### ISSUE TITLE
sample里面的例子，直接make报错

### ISSUE THREAD

**Issue by zhkzyth** [baidu/sofa-pbrpc#21]
hi：

我试了在sample里面的echo例子，直接make会报`ERROR: need snappy header`的错误提示。我是在mac osx 10.10的机子上面跑的。

我按照install教程里面的地址，把snappy1.1.2包下回来，也安装成功了。sofa-pbrpc也是安装成功的，能正常跑起来。

我看了下make脚本，貌似是SNAPPY_DIR这个变量没设置到之类的。

**Comment by fxsjy** [comment]
depends.mk 这个文件里面可以自定义：·depends.mk·

**Comment by zhkzyth** [comment]
@fxsjy 嗷嗷，谢谢~~刚刚解决了，我把`SNAPPY_DIR=/usr/local`加上就fix了，因为我是直接在snappy包下面`make install`，所以库是装在/usr/local下面的。

不过我又遇到两个个问题。

- mac上会报 -lrt 错误，貌似是librt在mac上不需要的，直接在makefile里面去掉这个选项就可以了，具体可以参考下面的[链接][1]。

- 貌似还需要创建一个`/lib`的的文件夹，不然会报文件夹找不到的错误。

[1]:http://stackoverflow.com/questions/1505402/library-not-found-for-lrt-with-qtcreator-mac-os

**Comment by cyshi** [comment]
Hi @zhkzyth 

两个问题

1. sample中的Makefile已经做了mac适配

2. /lib的文件夹是因为在depends.mk中有环境变量没有设置，你可以确认下是不是·$ZLIB_DIR·没有设置，这个应该是有一个warning，并不影响生成二进制
