### ISSUE TITLE
C#版本客户端

### ISSUE THREAD

**Issue by LazyPlanet** [baidu/sofa-pbrpc#219]
请问老板，什么时候开发C#版本的客户端呢？是不是可以借用supersocket的接口进行处理：
http://docs.supersocket.net/v1-6/zh-CN/The-Built-in-Common-Format-Protocol-Implementation-Templates
谢谢。

**Comment by qinzuoyan** [comment]
可以用HTTP的方式访问。
或者你写一个C#的客户端贡献进来？:-)

**Comment by LazyPlanet** [comment]
http 对于游戏行业还是不太合适，我倒是可以考虑写一个。哈哈。
感谢老板。 @qinzuoyan

**Comment by LazyPlanet** [comment]
我先关了吧。如果老板没时间就等等吧。我们做业务的也没那么多时间做，感谢。
