### ISSUE TITLE
客户端超时设置

### ISSUE THREAD

**Issue by lirunlong** [baidu/sofa-pbrpc#228]
设置超时  好像基本没用 比如我设置的是5ms  有时候都过了几十ms才超时  或者 rt 20几ms  也是正常返回。

版本是1.1.0

**Comment by scottzzq** [comment]
我也遇到同样的问题，设置超时时间100ms，但是发现180ms才返回，我也在找原因。

**Comment by cyshi** [comment]
看下这个 https://github.com/baidu/sofa-pbrpc/issues/218
