### ISSUE TITLE
GOOGLE_ATTRIBUTE_DEPRECATED 替换成   __attribute__((deprecated)) 

### ISSUE THREAD

**Issue by yuinm** [baidu/sofa-pbrpc#235]
GzipOutputStream(
      ZeroCopyOutputStream* sub_stream,
      Format format,
      int buffer_size = -1) GOOGLE_ATTRIBUTE_DEPRECATED;
是否需要把"GOOGLE_ATTRIBUTE_DEPRECATED"替换成GNU标准？ protobuf 新版已经没有这个宏定义了。

**Comment by qinzuoyan** [comment]
或者干脆去掉这个宏吧，如果没有影响的话

**Comment by yuinm** [comment]
好..
