### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by qlyzpqz** [baidu/sofa-pbrpc#35]
sofa-pbrpc，编译对g++的版本，有什么要求呢？我用g++ 4.8.2编译失败了，protubuf，用的是proto 3.0版本

g++ -O2         -pipe -W -Wall -fPIC -D_GNU_SOURCE -D__STDC_LIMIT_MACROS -DHAVE_SNAPPY -Isrc -I/usr/include -I/home/kentpeng/sofa-pbrpc/thirty/protobuf/include -I/home/kentpeng/sofa-pbrpc/thirty/snappy/include -I/home/kentpeng/sofa-pbrpc/thirty/zlib/include   -c -o src/sofa/pbrpc/boost_system_error_code.o src/sofa/pbrpc/boost_system_error_code.cc
src/sofa/pbrpc/boost_system_error_code.cc:440:1: internal compiler error: in function_and_variable_visibility, at ipa.c:815
 } // namespace boost
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
Preprocessed source stored into /tmp/ccpGeFhP.out file, please attach this to your bugreport.
make: *** [src/sofa/pbrpc/boost_system_error_code.o] Error 1

**Comment by cyshi** [comment]
试一下proto2可否编译

**Comment by qlyzpqz** [comment]
你们开发环境，具体用的g++版本是什么呢？看这个提示，是说是gcc-4.8的bug

**Comment by cyshi** [comment]
```c++
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.2-19ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1)
```

4.8.2 应该可以顺利通过编译，你可以再确认一下依赖库的版本

**Comment by qlyzpqz** [comment]
问题解决了，是通过修改了src/sofa/pbrpc/boost_system_error_code.cc文件，把51,52行的匿名命名空间注释掉，这个编译错误，才解决的，另外，还改了Makefile里，链接选项的顺序，才链接通过的，proto，还是用的3.0的版本，不是proto3导致的问题

**Comment by qlyzpqz** [comment]
sample里的Makefile，也有问题， server:  server.o $(PROTO_OBJ)，server.o放在$(RPOTO_OBJ)前面，先编译了server.cc，server.cc中，使用了pb.h文件，这个，实际要先用protoc编译pb文件，才会生成，也需要换一下顺序

**Comment by cyshi** [comment]
@qlyzpqz 我看了下sample里面的Makefile并没有你说的这个问题啊

[sample/echo/Makefile](https://github.com/baidu/sofa-pbrpc/blob/master/sample/echo/Makefile)

**Comment by qlyzpqz** [comment]
看了一下，原来的历史版本有过这个问题，应该是我本地的soft-pbrpc是比较老的版本，忘了更新了
