### ISSUE TITLE
resolve addr fail问题

### ISSUE THREAD

**Issue by 00k** [baidu/sofa-pbrpc#37]
rpc_channel对象初始化时会解析对端ip，如果解析失败会导致这个对象上后续所有的call_method全部失败，只能靠用户析构并重新创建channel。希望能在rpc层面解决一下，例如call_method时检查一下距上次解析失败的时间，适当的进行重试。

**Comment by qinzuoyan** [comment]
我的理解，解析失败这种问题通常是难以恢复的，有专门的RPC_ERROR_RESOLVE_ADDRESS错误码与之对应，此时程序应当退出；如果实在需要重解析，就重新创建channel。
