### ISSUE TITLE
发送缓冲区中的数据可能会发不完就被丢弃掉了

### ISSUE THREAD

**Issue by hhggit** [baidu/sofa-pbrpc#49]
sofa::pbrpc::RpcServerMessageStream<>::try_start_send()
    {
    ...
                    // now send
                    _sent_size = 0;
                    bool ret = _sending_message->Next(
                            reinterpret_cast<const void**>(&_sending_data), &_sending_size);
                    SCHECK(ret);
                    async_write_some(_sending_data, _sending_size);
                    started = true;
                    break;
    ...
    }

上面的`try_start_send`函数调用应该循环多次调用`Next`，否则可能会造成`_sending_message`中的数据未发送完成。

`sofa::pbrpc::RpcMessageStream<>`也有同样的问题

**Comment by qinzuoyan** [comment]
我觉得不会有这个问题，因为这里的send只是一次单独发送一批数据，不要求是一个完整的message，可能只是message的一部分，注意_sending_message和_sent_size都是类变量，所以在on_write_some()中会接着发后面的部分，直到整个message都发送出去。
你是在使用中遇到这样的情况了吗？

**Comment by hhggit** [comment]
多谢耐心回复。之前看代码没有太仔细，忽略该异步调用的完成函数，我应该实际跟踪运行下再考虑发起Issue，真的很抱歉。

**Comment by qinzuoyan** [comment]
不客气，有什么问题随时提出来
