### ISSUE TITLE
RpcServer的连接池问题咨询

### ISSUE THREAD

**Issue by gandalf000** [baidu/sofa-pbrpc#52]
sofa rpc的rpc server支持的连接数有办法控制么？

**Comment by qinzuoyan** [comment]
目前还没有，不过确实应该加一个。 working on it...

**Comment by qinzuoyan** [comment]
已实现并merge，参见上面

**Comment by leegons** [comment]
连接数控制这个功能能改成实时的吗？现在live stream count统计有一分钟的延迟，不能做到严格控制

**Comment by qinzuoyan** [comment]
_live_stream_count的更新在RpcServerImpl::TimerMaintain中进行，目前是每100ms更新一次，不会有1分钟的延迟（可能你看到的是每分钟打印一条统计日志）。
当然在这100ms内确实有超过连接数的可能，不过我开始没想到需要这么严格。你确定100ms的延迟有不能容忍吗？

**Comment by qinzuoyan** [comment]
@leegons ，连接数已经改为了实时值，这样live stream count可以做到严格控制。
参见issue #61 和 pr #62 ，已merge
