### ISSUE TITLE
change SOFA_PBRPC_VERSION to proper value before release

### ISSUE THREAD

**Issue by qinzuoyan** [baidu/sofa-pbrpc#54]
before making a new release, we should change the SOFA_PBRPC_VERSION macro in file "src/sofa/pbrpc/common.h" to proper value, to make it consistent.

**Comment by qinzuoyan** [comment]
just as above, the next release will be 1.1.1

**Comment by bluebore** [comment]
当前master分支上代码改动较大，特别是性能优化的部分，qa还在测试中，建议先pre-release一下~

**Comment by qinzuoyan** [comment]
目前并不打算发布1.1.1，只是发个issue提醒一下，以后在release之前需要先将SOFA_PBRPC_VERSION改为正确的值:)

**Comment by cyshi** [comment]
get it
