### ISSUE TITLE
Profiling 支持计划

### ISSUE THREAD

**Issue by cyshi** [baidu/sofa-pbrpc#64]
# 功能

用户通过连编 [gperftools](https://github.com/gperftools/gperftools) 库，即可查看server的profiling数据，数据展示支持文本和图片两种方式，server端不需要安装graphviz
# 设计细节
### 处理流程

``` c++
class Profiling
{
public:
    // 两个servlet注册到WebService，用于展示Profiling数据
    bool CpuProfiling(HTTPRequest, HTTPResponse);
    bool MemoryProfiling(HTTPRequest, HTTPResponse);
};
```
- 以CpuProfiling为例
  - 用户在浏览器中访问RPC的WebServer，路径为 /cpu，同时点击页面按钮开始进行Profiling
  - CpuProfiling中收到请求后，进行适当判断（参数检查，以及是否有正在进行的Profiling），然后开始Profiling，为了不阻塞IO线程，`Profiling` 中会增加一个线程用于进行profiling
  - Profiling线程函数中，启动Profiling，sleep指定时间后（可由用户指定，从浏览器参数中传入），退出Profiling，数据放入固定位置
  - 用户浏览器侧使用ajax循环检查数据是否ready
  - server端收到数据检查请求后，从后台拿到数据，返回用户浏览器

``` c++
class Profiling
{
public:
    // 两个servlet注册到WebService，用于展示Profiling数据
    bool CpuProfiling(HTTPRequest, HTTPResponse);
    bool MemoryProfiling(HTTPRequest, HTTPResponse);
private:
    // profiling 线程，专门负责进行Profiling
    ThreadGroupImplPtr _profiling_thread_group;
};
```
- 为了使server端不需要安装graphviz，需要在浏览器上执行 [viz.js](https://github.com/mdaines/viz.js/)，server只需要生成dot文件即可

增加 viz.js.cc

``` c++
static const std::string vizjs = "content of viz.js";
```

为了生成dot，增加 pprof.perl.cc

``` c++
static const std::string pprof = "content of pprof";
```
### 数据生成
- 为了方便用户使用(只连编，不改代码)，Profiling中增加对应的弱符号

``` c++
// file profiling.cc
extern "C"
{
    // cpu profiling需要的函数
    int __attribute__((weak)) ProfilerStart(const char* fname);
    void __attribute__((weak)) ProfilerStop();
}
```
- 同时在common.h中，增加两个touch函数，和一个宏开关

``` c++
// file common.h
#ifdef SOFA_PBRPC_PROFILING
#include <gperftools/profiler.h>
#endif

namespace sofa {
namespace pbrpc {

#ifdef SOFA_PBRPC_PROFILING
void touch_gperftools_profiler()
{
    SCHECK(false);
    ProfilerStart("function_never_run");
    ProfilerStop();
}

void touch_profiler()
{
    SCHECK(false);
    touch_gperftools_profiler();
}
#endif

}
}
```
- Server 的Profiling线程，在当前运行目录下新建profiling文件夹及生成对应数据
- Server 使用管道获取pprof.pl执行后生成的dot文件，返回浏览器

@qinzuoyan @bluebore 两位先看下

**Comment by bluebore** [comment]
好

**Comment by bengol** [comment]
不错，建议同时提供perf结果下载，在本地通过kcachegrind进行查看

**Comment by cyshi** [comment]
#155 closed
