### ISSUE TITLE
线程数据如何attach？

### ISSUE THREAD

**Issue by penser** [baidu/sofa-pbrpc#75]
线程初始化回调函数不存入任何参数（ExtClosure<bool()>* work_thread_init_func; ）求问线程数据如何attach上去呢？

**Comment by qinzuoyan** [comment]
ExtClosure可以pre-bind一些参数（闭包就是带有上下文的函数），譬如你可以这样使用（在sample/echo/server.cpp上修改）：
```
bool thread_init_func(int param1, const std::string& param2)
{
    std::cout << "param1=" << param1 << std::endl;
    std::cout << "param2=" << param2 << std::endl;
    return true;
}

int main()
{
    ... ...
    int param1 = 0;
    std::string param2;
    options.work_thread_init_func = sofa::pbrpc::NewPermanentExtClosure(&thread_init_func, param1, param2);
    ... ...
}
```

**Comment by penser** [comment]
thanks。
同bind可以附带一些参数，在响应回调函数里面如何取呢， 线程变量数据存在哪里，并且回调可以取到

比如：bool thread_init_func(void *data)
{
      data->parm = new Param();
      return true;
}

在服务回调中：
  virtual void Echo(google::protobuf::RpcController* controller,
                      const sofa::pbrpc::test::EchoRequest* request,
                      sofa::pbrpc::test::EchoResponse* response,
                      google::protobuf::Closure* done){
              // 通过controller？request、response取到线程数据？
}

**Comment by qinzuoyan** [comment]
你可以考虑使用线程局部变量，在thread_init_func中初始化线程局部变量，然后在Echo服务方法实现中使用线程局部变量

**Comment by penser** [comment]
echo服务回传的只有三个参数： controller request response，好像无法获取到线程的局部变量数据。

**Comment by qinzuoyan** [comment]
线程局部变量(Thread Local Storage)，使用方式可以类似全局变量，在GCC下有__thread关键字支持，你可以参考 http://blog.csdn.net/crazyhacking/article/details/19930389

**Comment by penser** [comment]
thanks！
