### ISSUE TITLE
生产环境中的上线切流量问题

### ISSUE THREAD

**Issue by jimmy-kuo** [baidu/sofa-pbrpc#78]
Hi：
一直有个问题想咨询下您，我看到wiki上有描述了client是支持链接探活的(针对server端服务不可用的情况)。但是，如果用于生产环境，那么肯定存在一个上线时切流的问题，所以想问下，有没有类似于zookeeper的机制，能够保障主动切流量且不影响线上服务的feature。
谢谢

**Comment by qinzuoyan** [comment]
这个问题是有考虑的。其实在公司内部的sofa-pbrpc已经支持了这个功能，就是使用zookeeper来动态获取server地址，只是在开源的时候没有放进来。
实现起来也很简单，具体做法就是：实现AddressProvider接口，该实现负责监听zookeeper节点的变动，当节点数据发生变动的时候（server增删），就调用EventHandler通知client。
你可以参考sample/multi_server_sample下的样例代码。wiki参见：[高级使用](https://github.com/baidu/sofa-pbrpc/wiki/%E9%AB%98%E7%BA%A7%E4%BD%BF%E7%94%A8)中的“多Server负载均衡与容错”这一节。

**Comment by jimmy-kuo** [comment]
ok，回头我再自己研究下实现方案，感谢回答
