### ISSUE TITLE
连接建立失败

### ISSUE THREAD

**Issue by cyshi** [baidu/sofa-pbrpc#80]
最新master代码

连接建立失败
`libsofa_pbrpc ERROR src/sofa/pbrpc/rpc_byte_stream.h:285] on_connect(): connect error: 10.195.113.13:7701: The descriptor does not fit into the select call's fd_set`

暂时没有复现 建个issue跟踪

**Comment by zd-double** [comment]
用户在使用内部gitlab上的sofa-pbrpc过程中，发现在会出现 "The descriptor does not fit into the select call's fd_set"的rpc error日志，通过使用gitlab上的代码复现确认在发送大量请求时rpc内部执行async_read、async_write、async_connect等异步操作时会出现上述问题。

通过追查确认原因如下：
1.  gitlab上sofa-pbrpc 的src/sofa/pbrpc/common.h 中引入boost/asio.hpp的头文件
2.  boost内部构造io_service时，如果LINUX_VERSION_CODE < 2.5.45，采用的是select_reactor作为异步实现。当前系统的LINUX_VERSION_CODE定义为 2.4.20，因此默认会使用select_reactor。
3.  当采用select调用是会有FD_SETSIZE=1024的限制，boost中当socket_descriptor > FD_SETSIZE,会产生fd_set_failure的错误，对应的error_message为"The descriptor does not fit into the select call's fd_set"。
4.  在sofa-pbrpc为保证boost异步实现采用epoll_reactor,在src/sofa/pbrpc/io_service.h中引入boost/asio.hpp之前先定义了BOOST_ASIO_HAS_EPOLL 1的宏。
5.  由于common.h引入boost/asio.hpp, common_internal.h中先引入common.h后引入io_service.h，会导致boost中io_service构造时采用select_reactor，当处理大量请求过程中，rpc_byte_stream.h中tcp::socket::async_read等异步操作中会造成fd_set_failure的错误。

该问题只在内部gitlab上存在，将去掉common.h中boost/asio.hpp予以修复。

**Comment by qinzuoyan** [comment]
common.h是对用户暴露的头文件，为了避免对用户暴露boost/asio.hpp，所以特意将对asio.hpp的使用封装在io_service.h中。内部gitlab代码怎么能直接在common.h中include
<boost/asio.hpp>呢？

2016-07-11 16:55 GMT+08:00 ZhangDi <notifications@github.com>:

**Comment by qinzuoyan** [comment]
@zd-double ，能找出这个原因，还是很赞的~
