### ISSUE TITLE
在mac下编译sample里面的例子error，怎么解决？

### ISSUE THREAD

**Issue by victorustc** [baidu/sofa-pbrpc#90]
g++ echo_service.pb.o server.o -o server ../../output/lib/libsofa-pbrpc.a /Users/wangdesheng/Desktop/code/cpp_program/sofa-pbrpc/lib/protobuf/output/lib/libprotobuf.a /Users/wangdesheng/Desktop/code/cpp_program/sofa-pbrpc/lib/snappy/output/lib/libsnappy.a -L/Users/wangdesheng/Desktop/code/cpp_program/sofa-pbrpc/lib/zlib/output/lib -lpthread -lz
Undefined symbols for architecture x86_64:
  "_ProfilerStart", referenced from:
      sofa::pbrpc::Profiling::CpuProfilingFunc() in libsofa-pbrpc.a(profiling.o)
      sofa::pbrpc::Profiling::DoCpuProfiling(sofa::pbrpc::Profiling::DataType) in libsofa-pbrpc.a(profiling.o)
  "_ProfilerStop", referenced from:
      sofa::pbrpc::Profiling::CpuProfilingFunc() in libsofa-pbrpc.a(profiling.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [server] Error 1

**Comment by cyshi** [comment]
mac系统下 在sample的Makefile中增加一行` LDFLAGS+=-undefined dynamic_lookup`

**Comment by qinzuoyan** [comment]
@cyshi ，把这个修复提交进来吧

**Comment by cyshi** [comment]
@victorustc 已经解决了 可以试试

**Comment by victorustc** [comment]
非常感谢，亲测没有问题！赞效率！
