### ISSUE TITLE
连续发送较大包(4MB)无法准确限速

### ISSUE THREAD

**Issue by liangjianqun** [baidu/sofa-pbrpc#92]
我通过max_throughput_out配置为10（限速为10MB/s）企图将发包的网络速度控制在10MB/s，但发现速度控制不住，远大于这个值。在我的环境不配置时速度为70MB/S，配置max_throughput_out为10后速度为42MB/S。

请问这个问题可以修正吗？

**Comment by qinzuoyan** [comment]
我觉得问题出在发送的包较大（4MB），现在限速为0.1秒为一个限速单位，每个单位中允许发送一个4MB的包，那么就能达到40MB/s。这确实是限速没有考虑大包的情况。
另外，既然你的包这么大，那么每秒最多能发两个，有没有考虑自己在外部控制一下呢？

**Comment by qinzuoyan** [comment]
@liangjianqun ，已经在上面的pr中修复该问题，请拉取最新代码测试

**Comment by liangjianqun** [comment]
赞！我看看

**Comment by byronyi** [comment]
有没有考虑用 linux traffic control 来做 fine grained rate limiting

**Comment by cyshi** [comment]
暂时没这个打算
