### ISSUE TITLE
curl请求sofa rpc server速度很慢

### ISSUE THREAD

**Issue by rabqiu** [baidu/sofa-pbrpc#95]
echo sample里面的client_http.sh，将post的"Hello, world!"替换为一个长度为1k字节的字符串，响应时间会增加到两秒钟左右。

**Comment by rabqiu** [comment]
libcurl期待状态码100的问题，已解决。

**Comment by qinzuoyan** [comment]
@rabqiu ，那么现在的速度是多少？

**Comment by rabqiu** [comment]
响应时间正常了，几毫秒。
